#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Read the centralized configuration
const config = JSON.parse(fs.readFileSync('config.json', 'utf8'));

// Generate JavaScript configuration
const jsConfig = `// Auto-generated configuration from config.json
// Do not edit this file manually - edit config.json instead

const CONFIG = ${JSON.stringify(config, null, 2)};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}

// Make available globally for browser
if (typeof window !== 'undefined') {
    window.CONFIG = CONFIG;
}
`;

// Ensure the directory exists
const assetsJsDir = path.dirname('../assets/js/config.js');
if (!fs.existsSync(assetsJsDir)) {
    fs.mkdirSync(assetsJsDir, { recursive: true });
}

// Write the generated configuration
fs.writeFileSync('../assets/js/config.js', jsConfig);

console.log('✅ Generated assets/js/config.js from config.json');

// Generate a simple config for the billing API
const billingApiConfig = `// Auto-generated billing API configuration
const BILLING_CONFIG = {
    bucketName: '${config.aws.bucket_name}',
    functionName: '${config.aws.billing_api.function_name}',
    // Note: CloudFront distribution ID and other dynamic values 
    // should be fetched from Terraform outputs or environment variables
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = BILLING_CONFIG;
}
`;

fs.writeFileSync('../assets/js/billing-config.js', billingApiConfig);
console.log('✅ Generated assets/js/billing-config.js');
